name: Build and Deploy Resume PDFs

on:
  push:
    branches: [main]
    paths:
      - 'resume/resume.en.tex'
      - 'resume/resume.ru.tex'
      - 'resume/resume.cls'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-lang-cyrillic

      - name: Compile EN Resume
        working-directory: resume
        run: pdflatex -interaction=nonstopmode resume.en.tex

      - name: Compile RU Resume
        working-directory: resume
        run: pdflatex -interaction=nonstopmode resume.ru.tex

      - name: Rename EN PDF
        run: mv resume/resume.en.pdf resume/spiridonov_en.pdf

      - name: Rename RU PDF
        run: mv resume/resume.ru.pdf resume/spiridonov_ru.pdf

      - name: Upload EN PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-en
          path: resume/spiridonov_en.pdf

      - name: Upload RU PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-ru
          path: resume/spiridonov_ru.pdf

      - name: Prepare deploy folder
        run: |
          mkdir -p public
          cp resume/spiridonov_en.pdf public/spiridonov_en.pdf
          cp resume/spiridonov_ru.pdf public/spiridonov_ru.pdf
          touch public/.nojekyll

      - name: Upload to Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4