name: Build and Deploy Resume PDFs

on:
  push:
    branches: [main]
    paths:
      - 'resume/resume.en.tex'
      - 'resume/resume.ru.tex'
      - 'resume/resume.cls'

jobs:
  build-en:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-lang-cyrillic

      - name: Compile EN Resume
        working-directory: resume
        run: pdflatex -interaction=nonstopmode resume.en.tex

      - name: Rename PDF
        run: mv resume/resume.en.pdf resume/en.pdf

      - name: Upload EN PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-en
          path: resume/en.pdf

      - name: Upload to Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: resume/en.pdf

  build-ru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-lang-cyrillic

      - name: Compile RU Resume
        working-directory: resume
        run: pdflatex -interaction=nonstopmode resume.ru.tex

      - name: Rename PDF
        run: mv resume/resume.ru.pdf resume/ru.pdf

      - name: Upload RU PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-ru
          path: resume/ru.pdf

      - name: Upload to Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: resume/ru.pdf

  deploy:
    needs: [build-en, build-ru]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download Pages Artifacts
        uses: actions/download-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
